### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [cbuijs/ut1#1]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/cbuijs/ut1/master/cryptojacking/domains). Thanks!

**Comment by cbuijs** [comment]
Hi @BitCannaGlobal,

Thanks for the info! However, I am not the maintainer of this lists. Just providing a repo with the unpacked/optimized versions of it.

The maintainer can be found here (including contact-info):
https://dsi.ut-capitole.fr/blacklists/index_en.php

You can also suggest to add/remove domains below:
https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

Hope this helps.

Cheers,
-Chris.

**Comment by BitCannaGlobal** [comment]
Good day Chris

Thanks for your update!
I will contact the link you provided.

With kind regards,
***@***.***
