### ISSUE TITLE
Whitelist comocomecami.com

### ISSUE THREAD

**Issue by columndeeply** [cbuijs/ut1#2]
Hi! comocomecami.com is listed on the "adult" and "porn" domain lists but its not a porn site, it should be whitelisted.

**Comment by cbuijs** [comment]
Hi @columndeeply,

I do not maintain this lists, I just supply a unpacked version of the archive.

Please email `fabrice.prigent@ut-capitole.fr` or go to https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi to report.
