### ISSUE TITLE
Removal of CBQ.COM.QA Domains

### ISSUE THREAD

**Issue by deFr0ggy** [cbuijs/ut1#5]
Hi,

Can you please have CBQ.COM.QA removed from all the files, i see there are multiple occurences in the list. This is an official domain of "Commercial Bank of Qatar". 

Appreciate your support. 

Regards,

Kamran Saifullah
Commercial Bank
Doha, Qatar

**Comment by cbuijs** [comment]
Hi @deFr0ggy,

Thanks for the headsup! But... I do not maintain this lists, I just supply a unpacked version of the archive.

Please email the maintainer at `fabrice.prigent@ut-capitole.fr` or go to https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi to report.

Cheers,
-Chris.
